spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketlock
    username: ticket_admin
    password: root_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: ticketlock_keyspace
    local-datacenter: datacenter1
    schema-action: create-if-not-exists

server:
  port: 8080

